name: build

on:
  push:
    branches:
      - master
      - ci
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * 6'

jobs:
  build:

    strategy:
      matrix:
        include:
          - {os: ubuntu-18.04, cc: gcc-10, cxx: g++-10}
          - {os: ubuntu-18.04, cc: clang-10, cxx: clang++-10}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Update apt-get cache
      run: sudo apt-get update

    - name: Install Ubuntu dependencies
      run: >
        sudo apt-get install
        g++-10
        clang-10
        libgfortran3
        gfortran
        libboost-all-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        libopenmpi-dev
        libblas-dev
        liblapack-dev
        libfftw3-dev
        libgmp-dev
        hdf5-tools
        libhdf5-dev
        python3-dev
        python3-numpy
        python3-scipy
        python3-matplotlib
        python3-h5py
        python3-mpi4py
        python3-mako
        python3-nbsphinx
        ipython3
        libclang-10-dev
        python3-clang-10
        libjs-mathjax

    - name: Build & install TRIQS
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        LIBCLANG_LOCATION: /usr/lib/x86_64-linux-gnu/libclang-10.so
      run: |
        if [[ "${CXX}" == clang* ]]; then
          CMAKE_CXX_FLAGS="-stdlib=libc++"
          DOCS="ON"
        else
          DOCS="OFF"
        fi
        git clone https://github.com/TRIQS/triqs --branch 3.0.x
        mkdir triqs/build && pushd triqs/build
        cmake ..                                                               \
          -DCMAKE_BUILD_TYPE=Release                                           \
          -DCMAKE_INSTALL_PREFIX=$HOME/install                                 \
          -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                               \
          -DLIBCLANG_LOCATION=${LIBCLANG_LOCATION}                             \
          -DMATHJAX_PATH=/usr/share/javascript/mathjax                         \
          -DBuild_Tests=OFF                                                    \
          -DBuild_Documentation=${DOCS}
        make -j2 install VERBOSE=1
        popd

    - name: Build SOM
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
      run: |
        source $HOME/install/share/triqsvars.sh
        if [[ "${CXX}" == clang* ]]; then
          CMAKE_CXX_FLAGS="-stdlib=libc++"
          DOCS="OFF" # FIXME
        else
          DOCS="OFF"
        fi
        mkdir build && pushd build
        cmake ..                                                               \
          -DCMAKE_BUILD_TYPE=Release                                           \
          -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS}"                               \
          -DTRIQS_INVENTORY_DIR="https://triqs.github.io/triqs/3.0.x"          \
          -DMATHJAX_PATH=/usr/share/javascript/mathjax                         \
          -DBuild_Documentation=${DOCS}
        make -j2 VERBOSE=1
        popd

    - name: Test SOM
      run: |
        pushd build
        source $HOME/install/share/triqsvars.sh
        ctest --output-on-failure
        popd

    - name: Prepare docs for deployment (FIXME)
      if: startsWith(matrix.cxx, 'clang') && false
      run: |
        pushd build
        find doc/html -name "*.html"                                           \
        -type f -exec sed -i 's/\/usr\/share\/javascript\/mathjax/\/som\/mathjax/g' {} \;
        cp -r /usr/share/javascript/mathjax doc/html/mathjax
        touch doc/html/.nojekyll
        popd

    - name: Deploy documentation
      if: github.ref == 'refs/heads/master' && startsWith(matrix.cxx, 'clang')
      uses: JamesIves/github-pages-deploy-action@4.1.0
      with:
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/doc/html
