name: Push image to Docker Hub

on:
  push:
    tags:
      - '[0-9]+\.[0-9]+\.[0-9]+'

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:

    - name: Resolve git tag name
      uses: rlespinasse/github-slug-action@v4.x

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: |
              ikrivenko/som:${{ env.GITHUB_REF_SLUG }}
              ikrivenko/som:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
